# This is a basic workflow to help you get started with Actions

name: Development container registry

# Controls when the workflow will run
on: [push,pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on-push:
    # Check event
    if: github.event_name == 'push'
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: "development"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

#       - name: Build an image
#         run: |
#          docker build -f Dockerfile.dev -t $IMAGE_NAME .
        
      - name: Login into registry
        run: echo $IMAGE_NAME
#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
#       - name: Push to registry
#         run: |
#           IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY/$BRANCH_NAME:latest
#           docker tag $IMAGE_NAME $IMAGE_ID
#           docker push $IMAGE_ID
