name: Semantic release

on:
  push:
    branches:
      - master
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
       - name: Check direcotry
       - shell: bash
       - run: ls -a
       
       - name: Check direcotry
       - uses: actions/checkout@v2
       - shell: bash
       - run: ls -a
    
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          dry_run: true
          semantic_version: 17.3.7
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
