name: Semantic release

on:
  push:
    branches:
      - master
      - hotfix

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/codeql.yml@v1
    
  publish:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn add conventional-changelog-conventionalcommits

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
